language: r
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

r:
 - release 
 - devel
r_check_args: --as-cran 
warnings_are_errors: true

before_install:
    - export DISPLAY=:99.0

after_success:
  - Rscript -e 'library("covr");codecov(type="test")'
