#+BEGIN_HTML
<a href="https://travis-ci.org/bozenne/BuyseTest"><img src="https://travis-ci.org/bozenne/BuyseTest.svg?branch=master"></a>
<a href="http://cran.rstudio.com/web/packages/BuyseTest/index.html"><img src="http://www.r-pkg.org/badges/version/BuyseTest"></a>
<a href="http://cranlogs.r-pkg.org/downloads/total/last-month/BuyseTest"><img src="http://cranlogs.r-pkg.org/badges/BuyseTest"></a>
<a href="https://ci.appveyor.com/project/bozenne/BuyseTest"><img src="https://ci.appveyor.com/api/projects/status/github/bozenne/BuyseTest?svg=true" alt="Build status"></a>
<a href="http://www.gnu.org/licenses/gpl-3.0.html"><img src="https://img.shields.io/badge/License-GPLv3-blue.svg" alt="License"></a>
#+END_HTML

* BuyseTest

*BuyseTest* is a package for the R software
(https://www.r-project.org/) implementing generalized pairwise
comparisons (GPC). GPC compare two groups of observations
(intervention vs. control group) regarding several prioritized
endpoints. The net benefit, win ratio, and Mann-Whitney parameter can
then be estimated and corresponding confidence intervals and p-values
can be estimated using resampling methods or the asymptotic
U-statistic theory. The software enables the use of thresholds of
minimal importance difference, stratification, and corrections to deal
with right-censored endpoints.

The Generalized Pairwise Comparisons form all possible pairs of
observations, one observation being taken from the intervention group
and the other is taken from the control group, and compare the value
of their endpoints.

If the difference in endpoint value between the two observations of
the pair is greater than the threshold of clinical relevance, the pair
is classified as favorable (i.e. win). If the difference is lower than
minus the threshold of clinical relevance the pair is classified as
unfavorable (i.e. loss).  Otherwise the pair is classified as
neutral. In presence of censoring, it might not be possible to compare
the difference to the threshold. In such cases the pair is classified
as uninformative.
 
Simultaneously analysis of several endpoints is performed by
prioritizing the endpoints, assigning the highest priority to the
endpoint considered the most clinically relevant.  The endpoint with
highest priority is analyzed first, and neutral and uninformative pair
are analyzed regarding endpoint of lower priority.

* Installation

You can download the latest stable version on =CRAN= using:
#+BEGIN_SRC R :exports both :eval never
install.packages("BuyseTest")
#+END_SRC

or download the development version from =GitHub=:
#+BEGIN_SRC R :exports both :eval never
library(devtools)
install_github("bozenne/BuyseTest")
#+END_SRC

* Citation
To cite this package in a publications please use:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
citation("BuyseTest")
#+END_SRC

#+RESULTS:
#+begin_example

To cite the 'BuyseTest' package in publications use the citation from
2020.

To cite the statistical method used by BuyseTes 'BuyseTest' package,
use the citation from: (2010) when using BuyseTest binary/continous
endpoint or time to event endpoints with scoring.rule="Gehan", (2016)
when using BuyseTest with time to event endpoint with
scoring.rule="Peron".

  Brice Ozenne and Julien Peron (2020). BuyseTest: Implementation of
  the Generalized Pairwise Comparisons. R package version 1.9.1.

  Buyse, M. (2010), Generalized pairwise comparisons of prioritized
  outcomes in the two-sample problem. Statistics in medicine, 29:
  3245-3257. doi:10.1002/sim.3923

  Peron, M. et al. (2018), An extension of generalized pairwise
  comparisons for prioritized outcomes in the presence of censoring.
  Statistical methods in medical research, 27: 1230-1239.
  https://doi.org/10.1177/0962280216658320

To see these entries in BibTeX format, use 'print(<citation>,
bibtex=TRUE)', 'toBibtex(.)', or set
'options(citation.bibtex.max=999)'.
#+end_example

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
toBibtex(citation("BuyseTest"))
#+END_SRC

#+RESULTS:
#+begin_example
@Manual{,
  title = {BuyseTest: Implementation of the Generalized Pairwise Comparisons},
  author = {Brice Ozenne and Julien Peron},
  year = {2020},
  note = {R package version 1.9.1},
}

@Article{,
  title = {Generalized pairwise comparisons of prioritized outcomes in the two-sample problem},
  author = {Marc Buyse},
  year = {2010},
  volume = {29},
  number = {30},
  pages = {3245--3257},
  journal = {Statistics in medicine},
  doi = {10.1002/sim.3923},
}

@Article{,
  title = {An extension of generalized pairwise comparisons for prioritized outcomes in the presence of censoring},
  author = {{P{'e}ron} and {Julien} and {Buyse} and {Marc} and {Ozenne} and {Brice} and {Roche} and {Laurent} and {Roy} and {Pascal}},
  year = {2018},
  volume = {27},
  number = {4},
  pages = {1230--1239},
  journal = {Statistical methods in medical research},
  doi = {10.1177/0962280216658320},
}
#+end_example

* Functionalities
See the vignette "Overview of the package BuyseTest" in [[./vignettes/overview.pdf]]
