#+BEGIN_HTML
<a href="https://travis-ci.org/bozenne/BuyseTest"><img src="https://travis-ci.org/bozenne/BuyseTest.svg?branch=master"></a>
<a href="http://cran.rstudio.com/web/packages/BuyseTest/index.html"><img src="http://www.r-pkg.org/badges/version/BuyseTest"></a>
<a href="http://cranlogs.r-pkg.org/downloads/total/last-month/BuyseTest"><img src="http://cranlogs.r-pkg.org/badges/BuyseTest"></a>
<a href="https://ci.appveyor.com/project/bozenne/BuyseTest"><img src="https://ci.appveyor.com/api/projects/status/github/bozenne/BuyseTest?svg=true" alt="Build status"></a>
#+END_HTML

* BuyseTest

*BuyseTest* is a package for the R software
(https://www.r-project.org/) implementing generalized pairwise
comparisons (GPC). This enables to compare two groups of observations
in randomized trials(e.g treated vs. control patients) on several
prioritized outcomes. Pairwise comparisons require consideration of
all possible pairs of individuals, one taken from the treatment group
and the other taken from the control group. The outcomes of the two
individuals forming a pair are compared. Thresholds of minimal
clinically significant differences can be defined. It is possible to
analyse simultaneously several outcomes by prioritizing the variables
that capture them. The highest priority is assigned to the variable
considered the most clinically relevant.  A natural way of handling
uninformative or neutral pairs is to consider the outcomes in
descending order of priority: whenever a pair is uninformative or
neutral for an outcome of higher priority, the outcomes of lower
priority are examined In the case of time-to-event endpoint, four
methods to handle censored observations are available in this package
(Gehan, Peto, Efron, and Peron).

* Installation

You can download the latest stable version on =CRAN= using:
#+BEGIN_SRC R :exports both :eval never
install.packages("BuyseTest")
#+END_SRC

or download the development version from =GitHub=:
#+BEGIN_SRC R :exports both :eval never
library(devtools)
install_github("bozenne/BuyseTest")
#+END_SRC

* Citation
To cite this package in a publications please use:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
citation("BuyseTest")
#+END_SRC

#+RESULTS:
#+begin_example

To cite the 'BuyseTest' package in publications use the citation from
2018.

To cite the statistical method used by BuyseTes 'BuyseTest' package,
use the citation from: (2010) when using BuyseTest binary/continous
endpoint or time to event endpoints with method.tte="Gehan", (2016)
when using BuyseTest with time to event endpoint with
method.tte="Peron".

  Brice Ozenne and Julien Peron (2018). BuyseTest: Implementation of
  the Generalized Pairwise Comparisons. R package version 1.4.2.

  Buyse, M. (2010), Generalized pairwise comparisons of prioritized
  outcomes in the two-sample problem. Statistics in medicine, 29:
  3245-3257. doi:10.1002/sim.3923

  Peron, M. et al. (2018), An extension of generalized pairwise
  comparisons for prioritized outcomes in the presence of censoring.
  Statistical methods in medical research, 27: 1230-1239.
  https://doi.org/10.1177/0962280216658320

To see these entries in BibTeX format, use 'print(<citation>,
bibtex=TRUE)', 'toBibtex(.)', or set
'options(citation.bibtex.max=999)'.
#+end_example

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
toBibtex(citation("BuyseTest"))
#+END_SRC

#+RESULTS:
#+begin_example
@Manual{,
  title = {BuyseTest: Implementation of the Generalized Pairwise Comparisons},
  author = {Brice Ozenne and Julien Peron},
  year = {2018},
  note = {R package version 1.4.2},
}

@Article{,
  title = {Generalized pairwise comparisons of prioritized outcomes in the two-sample problem},
  author = {Marc Buyse},
  year = {2010},
  volume = {29},
  number = {30},
  pages = {3245--3257},
  journal = {Statistics in medicine},
  doi = {https://doi.org/10.1002/sim.3923},
}

@Article{,
  title = {An extension of generalized pairwise comparisons for prioritized outcomes in the presence of censoring},
  author = {{P{'e}ron} and {Julien} and {Buyse} and {Marc} and {Ozenne} and {Brice} and {Roche} and {Laurent} and {Roy} and {Pascal}},
  year = {2018},
  volume = {27},
  number = {4},
  pages = {1230--1239},
  journal = {Statistical methods in medical research},
  doi = {https://doi.org/10.1177/0962280216658320},
}
#+end_example

* Functionalities
See the vignette "Overview of the package BuyseTest" in =./vignettes/overview.org=
