#+TITLE: Comparaison de méthodes d'inférence dans le cadre des comparaisons par paires généralisées

#+LaTeX: \author{}
#+LaTeX: \maketitle{}

Les comparaisons par paires généralisées (citep:buyse2010generalized,
citep:peron2018extension) est une méthode d'analyse statistique
permettant de comparer un groupe de patients ayant reçu un traitement
à un groupe contrôle en considérant plusieurs critères de
jugement. Cette méthode permet d'estimer le bénéfice net en faveur du
traitement valant 1 lorsque le traitement a été favorable pour tous
les patients, -1 lorsqu'il a toujours été défavorable, et 0 lorsque
l'effet traitement au niveau groupe est nul. 

\bigskip

Afin de pouvoir tester si l'effet traitement est favorable or de
calculer son intervalle de confiance, il est nécessaire de connaître la
distribution statistique du bénéfice net en faveur du traitement. Pour
cela plusieurs méthodes sont envisageables:
- méthode de permutation citep:buyse2010generalized
- techniques de bootstrap citep:dong2016generalized
- utilisation de la distribution asymptotique citep:luo2015alternative, citep:bebu2015large

L'objectif du stage est de comparer ces méthodes en terme d'hypothèses
nécessaires à leur validité, contrôle de l'erreur de type 1 en
échantillons finis, et ressources informatiques nécessaires à leur
utilisation. L'évaluation de ces méthodes se fera en relation avec la
librairie =BuyseTest= du logiciel R qui implémente les comparaisons par
paires généralisées. Cette librairie permet d'utiliser une méthode de
permutation ainsi que deux types de boostrap. L'estimation de la
distribution asymptotique est actuellement en cours de développement;
l'étudiant pourra prendre part à ce développement s'il souhaite un
sujet de stage plus théorique.

\bigskip

*Durée*: 6 mois

*Début du stage*: ??

*Laboratoire de rattachement*: Service de biostatistiques des hospices de Lyon.

*Profil*: Le candidat devra être en formation au sein d’un Master 2 à
dominante statistique ou dans école d’ingénieur avec une spécialisation en statistique.

*Encadrants*: Julien Péron (...)  Brice Ozenne (Post doctorant au
département de biostatistique de l'université de Copenhague, en charge
du développement et de la maintenance du code du package =BuyseTest=)

*Contact*: Julien Péron (julien.peron@chu-lyon.fr) 

\bigskip

bibliographystyle:apalike
[[bibliography:bibliography.bib]]


# @@latex:any arbitrary LaTeX code@@

*  R :noexport:

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(BuyseTest)
df.data <- simBuyseTest(1e2, n.strata = 2)
BT <- BuyseTest(Treatment ~ TTE(eventtime, censoring = status), 
                data=df.data, n.resampling = 10)
summary(BT)
#+END_SRC

#+RESULTS:
#+begin_example
Settings (punctual estimation) 
   > treatment groups: Control = 0 and Treatment = 1
   > 1 endpoint: 
      |priority endpoint  type          operator            threshold censoring |
      |1        eventtime time to event higher is favorable 1e-12     status    |
   > management of neutral pairs : re-analyzed using endpoints of lower priority (if any) 
   > management of censored survival pairs : imputation using Kaplan Meier stratified by treatment group 
   > weights of the pairs relatively to the enpoints: 
<0 x 0 matrix>
   > intervals thresholds for survival endpoints: 
                   eventtime   
threshold interval "[0 ; Inf] "

Punctual estimation (done) 
Permutation test (1 cpu, seed 10)
   |                                                  | 0 % ~calculating     |+++++                                             | 10% ~00s             |++++++++++                                        | 20% ~00s             |+++++++++++++++                                   | 30% ~00s             |++++++++++++++++++++                              | 40% ~00s             |+++++++++++++++++++++++++                         | 50% ~00s             |++++++++++++++++++++++++++++++                    | 60% ~00s             |+++++++++++++++++++++++++++++++++++               | 70% ~00s             |++++++++++++++++++++++++++++++++++++++++         | 80% ~00s             |+++++++++++++++++++++++++++++++++++++++++++++    | 90% ~00s             |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
        Generalized pairwise comparison with 1 prioritized endpoint

 > statistic       : net chance of a better outcome (delta: endpoint specific, Delta: global) 
 > null hypothesis : Delta == 0 
 > permutation test: 10 samples, confidence level 0.95 
 > treatment groups: 0 (control) vs. 1 (treatment) 
 > censored pairs  : imputation using Kaplan Meier stratified by treatment group

 > results
  endpoint threshold total favorable unfavorable neutral uninf  delta  Delta CI [2.5 ; 97.5] p.value 
 eventtime     1e-12   100     53.01       44.22       0  2.78 0.0879 0.0879 [-0.046;0.3004]     0.6 
NOTE: confidence intervals computed under the null hypothesis
#+end_example




* CONFIG :noexport:
# #+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Copenhagen, Denmark}
#+LANGUAGE:  en
#+LaTeX_CLASS: org-article
#+OPTIONS:   title:nil  author:nil date:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t

** Code
#+PROPERTY: header-args :session *R*
#+PROPERTY: header-args :tange yes % extract source code: http://orgmode.org/manual/Extracting-source-code.html
#+PROPERTY: header-args :eval yes :cache no
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.5,0,0}}}

** Display 
#+LATEX_HEADER: \RequirePackage{colortbl} % arrayrulecolor to mix colors
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER:\usepackage{authblk} % enable several affiliations (clash with beamer)

** Image
#+LATEX_HEADER: \RequirePackage{epstopdf} % to be able to convert .eps to .pdf image files

** Latex command
#+LaTeX_HEADER: %
#+LaTeX_HEADER: %%%% additional latex commands %%%%
#+LaTeX_HEADER: %

